import os
from typing import Any


SUPPORTED_LANGUAGES = ("uk", "en")


TRANSLATIONS = {
    "en": {
        "lang_name": "English",
        "app_title": "StepPrep",
        "desktop_system_title": "StepPrep Emergency System",
        "desktop_platform_subtitle": "Professional Monitoring Platform v2.1",
        "demo_mode_enabled": "Demo Mode Enabled",
        "monitor_tab": "1 Monitor",
        "shelter_tab": "2 Shelter",
        "shelter_feed_tab": "2 Shelter feed",
        "supplies_tab": "3 Go bag",
        "settings_tab": "4 Settings",
        "supplies_short": "go bag",
        "settings_short": "settings",
        "add_shelter_short": "add shelter",
        "risk": "Risk",
        "risk_normal": "NORMAL",
        "risk_elevated": "ELEVATED",
        "mode": "Mode",
        "reason": "Reason",
        "motion": "Motion",
        "body_motion": "Body motion",
        "body_collision": "Hit",
        "flash": "Flash",
        "gesture": "Gesture",
        "number": "Number",
        "google_account": "Google account",
        "login_register": "L login/register",
        "alarm_action_line": "ALARM: action in {seconds:04.1f}s | X cancel | C confirm | 2 shelter | 3 go bag | M map",
        "shelter_feed_header": "Shelter feed",
        "alarm": "Alarm",
        "ready": "ready",
        "active": "ACTIVE",
        "call": "Call",
        "alarm_feed_opened": "Alarm link: this feed opened automatically because danger was detected.",
        "keys_shelter": "Keys: 1 monitor | 2 shelter feed | 3 go bag | 4 settings | A add shelter | G Google search | L login | M map | Q quit",
        "nearest": "NEAREST",
        "distance_unknown": "distance unknown",
        "distance": "Distance",
        "address": "Address",
        "address_not_provided": "address not provided",
        "phone": "phone",
        "phone_not_provided": "not provided",
        "open_route_note": "press M to open this route/search in Google Maps",
        "no_shelter_candidates": "No shelter candidates yet.",
        "set_google_hint": "Set GOOGLE_MAPS_API_KEY + USER_LAT + USER_LON, then press G.",
        "add_shelters_hint": "Or add local shelters and metro stations to shelters.json.",
        "press_map_hint": "Press M to open a Google Maps search without API.",
        "last_map_url": "Last map URL: {url}",
        "settings_header": "Settings",
        "supplies_header": "Necessary things to take",
        "supplies_custom_header": "Customize go bag",
        "supplies_editor_hint": "Edit one item per line: Title: details. The checklist updates while you type.",
        "supplies_empty": "No go bag items yet.",
        "supplies_saved": "Go bag saved to {path}.",
        "supplies_save_failed": "Could not save go bag: {error}",
        "supplies_load_failed": "Could not load custom go bag: {error}",
        "supplies_reset_done": "Go bag reset to defaults.",
        "supplies_keys": "Keys: 1 monitor | 2 shelters | 3 go bag | 4 settings | A add shelter | L login | M map | Q quit",
        "settings_keys": "1 monitor | 2 shelters | 3 go bag | 4 settings | A add shelter | G refresh | L login | M map | Q quit",
        "button_cancel": "Cancel alarm",
        "button_confirm": "Confirm now",
        "button_search": "Search shelters",
        "button_auto_shelters": "Auto nearby",
        "button_login": "Google login",
        "button_map": "Open map",
        "button_language": "Switch language",
        "button_add_shelter": "Add shelter",
        "button_save_supplies": "Save go bag",
        "button_reset_supplies": "Reset defaults",
        "button_quit": "Quit",
        "emergency_contact": "Emergency contact",
        "camera": "Camera",
        "live_camera_feed": "Live camera feed",
        "camera_online": "ONLINE",
        "detection_systems": "Detection systems",
        "location_status": "Location",
        "not_set": "not set",
        "manual_shelter_header": "Add shelter",
        "search_query_label": "Search query:",
        "shelter_name_label": "Shelter name:",
        "address_label": "Address:",
        "latitude_label": "Latitude:",
        "longitude_label": "Longitude:",
        "phone_label": "Phone:",
        "note_label": "Note:",
        "manual_shelter_hint": "Press A after setting NEW_SHELTER_NAME plus address or coordinates.",
        "shelter_add_ready": "A add shelter from NEW_SHELTER_*",
        "shelter_add_missing": "Set NEW_SHELTER_NAME and address or coordinates before pressing A.",
        "shelter_added": "Shelter added: {name}",
        "shelter_add_failed": "Could not add shelter: {error}",
        "maps_account_hint": "Login keeps Google Maps ready in the browser account you use later.",
        "demo": "DEMO",
        "real": "REAL",
        "language": "Language",
        "language_toggled": "Language switched to {language}.",
        "google_not_searched": "Google Maps: not searched",
        "google_set_api": "Google Maps: set GOOGLE_MAPS_API_KEY",
        "google_set_api_places": "Google Maps: set GOOGLE_MAPS_API_KEY to search Places",
        "google_waiting_location": "Google Maps: waiting for location",
        "google_set_location": "Google Maps: set USER_LAT and USER_LON first",
        "google_searching": "Google Maps: searching...",
        "google_found": "Google Maps: found {count} candidates",
        "google_found_shelters": "Google Maps: found {count} shelter candidates",
        "google_search_running": "Google Maps: search already running",
        "google_search_failed": "Google Maps search failed: {error}",
        "google_search_fallback": "Google Maps: fallback search opened in browser",
        "google_error": "Google Maps error: {message}",
        "auto_location_detecting": "Auto: detecting location...",
        "auto_location_found": "Auto: location detected.",
        "auto_location_failed": "Auto: could not detect location. Set USER_LAT/USER_LON or enable location services.",
        "auto_shelter_searching": "Auto: searching nearby metro shelters...",
        "auto_shelter_found": "Auto: found {count} nearby metro shelter candidates within {radius} m.",
        "auto_shelter_no_candidates": "Auto: no nearby metro shelters found within {radius} m.",
        "auto_shelter_failed": "Auto shelter search failed: {error}",
        "passive_fallback_ready": "Passive mode: Google Maps fallback is ready",
        "passive_waiting_location": "Passive mode: set USER_LAT and USER_LON for nearest shelters",
        "google_shelter_name": "Google Maps shelter",
        "google_candidate_note": "Google Maps Places candidate",
        "google_candidate_note_desktop": "Found through Google Maps Places API",
        "google_maps_shelter_query": "metro station shelter",
        "google_maps_near": "near",
        "metro_station_shelter": "Metro station shelter",
        "metro_entrance_shelter": "Metro entrance shelter",
        "osm_shelter_note": "Found automatically through OpenStreetMap/Overpass.",
        "google_maps_fallback_name": "Google Maps shelter/metro search",
        "google_maps_fallback_note": "Fallback candidate: opens Google Maps search for shelters and metro stations.",
        "google_maps_no_location": "Google Maps search, no USER_LAT/USER_LON set",
        "shelter_file_missing": "Shelter file not found: {path}",
        "shelter_file_read_failed": "Could not read shelter file {path}: {error}",
        "unnamed_shelter": "Unnamed shelter",
        "shelter_map_opened": "Shelter map opened.",
        "open_url": "Open this URL: {url}",
        "audio_disabled_install": "Audio disabled: install sounddevice with `pip install sounddevice`.",
        "audio_disabled_microphone": "Audio disabled: could not open microphone: {error}",
        "gesture_disabled_install": "Gesture detection disabled: install mediapipe with `pip install mediapipe`.",
        "gesture_model_missing": "Gesture detection disabled: model file not found: {path}",
        "gesture_tasks_failed": "Gesture detection disabled: could not create MediaPipe Tasks HandLandmarker from {path}: {error}",
        "gesture_reinstall_hint": "Try: pip install --upgrade --force-reinstall mediapipe",
        "gestures_disabled": "gestures disabled",
        "no_hand": "no hand",
        "hand_visible": "hand visible",
        "gesture_detected": "Gesture: {gesture} {seconds:.1f}s",
        "hand_motion_label": "hand motion {score:.2f}",
        "body_motion_overlay": "body moving {direction} {score:.2f} | hit {hit}",
        "body_hit_overlay": "HIT",
        "hit_yes": "hit",
        "hit_no": "no hit",
        "direction_unknown": "unknown",
        "direction_still": "still",
        "direction_left": "left",
        "direction_right": "right",
        "direction_up": "up",
        "direction_down": "down",
        "direction_up_left": "up-left",
        "direction_up_right": "up-right",
        "direction_down_left": "down-left",
        "direction_down_right": "down-right",
        "body_direction": "Direction",
        "thumbs_up_help_label": "thumbs-up help",
        "fist_help_label": "fist help",
        "direct_move_help_label": "direct movement help",
        "monitoring": "monitoring",
        "disaster_estimate": "Disaster estimate",
        "safe_area": "no immediate hazard",
        "disaster_tornado": "Tornado",
        "disaster_flood": "Flood",
        "disaster_fire": "Fire",
        "hazard_none": "none",
        "hazard_far": "far",
        "hazard_medium": "medium",
        "hazard_near": "near",
        "alarm_cancelled": "alarm cancelled",
        "weapon_detected": "Weapon detected: {kind}",
        "knife_detected": "Knife detected",
        "gun_detected": "Gun detected",
        "weapon_moving": "Moving weapon detected",
        "object_speed_alert": "Fast small object movement detected",
        "sharp_impulse_reason": "sharp impulse sound: {rms_db:.1f} dBFS, peak {peak:.2f}",
        "sustained_sound_reason": "sustained high-frequency loud sound: {rms_db:.1f} dBFS",
        "bright_flash_reason": "sudden bright flash: score {score:.2f}",
        "sudden_motion_reason": "sudden motion: score {score:.2f}",
        "body_direction_reason": "body moving {direction}: score {score:.2f}",
        "body_collision_reason": "body hit/collision detected {direction}: score {score:.2f}",
        "manual_gesture_reason": "manual help gesture: {gesture}, held {seconds:.1f}s",
        "action_cooldown": "Action skipped: cooldown is active.",
        "demo_action": "DEMO: emergency action would run now. Target number: {number}. Reason: {reason}",
        "local_action_finished": "Local action finished with exit code {code}.",
        "twilio_missing": "Real action is enabled, but Twilio config is missing: {missing}",
        "twilio_message": "Automatic emergency alert. A possible life threatening situation was detected. Reason: {reason}. Please verify and dispatch help if appropriate.",
        "twilio_sent": "Twilio call request sent: HTTP {status}. {body}",
        "twilio_failed": "Could not place Twilio call: {error}",
        "alarm_status": "ALARM: press X to cancel, C to call now",
        "desktop_mode_print": "Mode: {mode}",
        "desktop_target_print": "Target emergency number/contact: {number}",
        "desktop_keys_print": "Press Q quit, X cancel, C confirm, 1 monitor, 2 shelters, 3 go bag, 4 settings, O auto nearby, A add shelter, G Google search, L login, M map, T language.",
        "desktop_ui_missing": "Desktop UI needs tkinter and Pillow. Install Pillow with `pip install Pillow`; tkinter is included with the standard Windows Python installer.",
        "google_login_required_failed": "Google login is required, but registration did not finish.",
        "evidence_saved": "Evidence saved: {path}",
        "camera_read_failed": "Could not read frame from camera.",
        "camera_open_failed": "Could not open camera {index}.",
        "camera_opened_debug": "Camera opened: index={index}, isOpened={opened}",
        "window_create_failed": "Failed to create display window: {error}",
        "entering_main_loop": "Entering main loop and showing window",
        "google_account_not_registered": "Google account: not registered",
        "google_account_set_client": "Google account: set GOOGLE_OAUTH_CLIENT_ID first",
        "google_account_callback_failed": "Google account: could not start local callback: {error}",
        "opening_google_signin": "Opening Google sign-in: {url}",
        "google_login_running": "Google account: login is already running",
        "google_account_opened": "Google account page opened. For full OAuth set GOOGLE_OAUTH_CLIENT_ID, or set GOOGLE_ACCOUNT_EMAIL for a local profile.",
        "google_profile_saved_env": "Google account: saved local profile {email}",
        "google_account_error": "Google account: {error}",
        "google_account_timeout": "Google account: login timed out or was cancelled",
        "google_token_error": "Google account: token error: {error}",
        "google_profile_error": "Google account: profile error: {error}",
        "google_profile_incomplete": "Google account: incomplete Google profile response",
        "google_account_registered": "Google account: registered {email}",
        "google_signin_failed_page": "Google sign-in failed. You can close this tab.",
        "google_signin_done_page": "Google sign-in finished. You can return to StepPrep.",
        "mobile_ready": "Ready",
        "mobile_alarm_active": "ALARM ACTIVE",
        "mobile_sos": "SOS / Trigger Alarm",
        "mobile_manual_sos": "Manual mobile SOS",
        "mobile_dial": "Dial Emergency Contact",
        "mobile_open_feed": "Open Shelter Feed",
        "mobile_register_google": "Register / View Google Account",
        "mobile_hooks_note": "Mobile audio/video detection hooks can be added after Android permissions are tested.",
        "mobile_shelter_feed": "Shelter Feed",
        "mobile_search": "Search",
        "mobile_map": "Map",
        "mobile_back": "Back",
        "mobile_empty_feed": "No shelter candidates yet.\nPress Search, enable Google Maps API, or add shelters/metro stations to shelters.json.",
        "mobile_open_map": "Open map",
        "mobile_start_gps": "Start GPS",
        "mobile_google_oauth": "Open Google OAuth in desktop app",
        "mobile_toggle_language": "Switch language",
        "mobile_emergency_contact": "Emergency contact: {number}",
        "mobile_location": "Location: {location}",
        "mobile_maps": "Maps query: {query}\nAPI key: {api_key}",
        "mobile_waiting_location": "waiting for USER_LAT/USER_LON or GPS",
        "api_configured": "configured",
        "api_not_configured": "not configured",
        "gps_desktop": "GPS is available on Android builds; desktop uses USER_LAT/USER_LON.",
        "gps_starting": "GPS: starting...",
        "gps_updated": "GPS: location updated",
        "mobile_alarm_status": "Alarm: {reason}. Shelter feed opened.",
        "not_registered": "not registered",
        "registered": "registered",
        "metro_note": "Metro stations are also treated as shelter candidates.",
    },
    "uk": {
        "lang_name": "Українська",
        "app_title": "StepPrep",
        "desktop_system_title": "Екстрена система StepPrep",
        "desktop_platform_subtitle": "Професійна платформа моніторингу v2.1",
        "demo_mode_enabled": "Демо-режим увімкнено",
        "monitor_tab": "1 Моніторинг",
        "shelter_tab": "2 Укриття",
        "shelter_feed_tab": "2 Стрічка укриттів",
        "supplies_tab": "3 Тривожна сумка",
        "settings_tab": "4 Налаштування",
        "supplies_short": "речі",
        "settings_short": "налаштування",
        "add_shelter_short": "додати укриття",
        "risk": "Ризик",
        "risk_normal": "НОРМА",
        "risk_elevated": "ПІДВИЩЕНО",
        "mode": "Режим",
        "reason": "Причина",
        "motion": "Рух",
        "body_motion": "Рух тіла",
        "body_collision": "Удар",
        "flash": "Спалах",
        "gesture": "Жест",
        "number": "Номер",
        "google_account": "Google-акаунт",
        "login_register": "L вхід/реєстрація",
        "alarm_action_line": "ТРИВОГА: дія через {seconds:04.1f}с | X скасувати | C підтвердити | 2 укриття | 3 речі | M карта",
        "shelter_feed_header": "Стрічка укриттів",
        "alarm": "Тривога",
        "ready": "готово",
        "active": "АКТИВНА",
        "call": "Дзвінок",
        "alarm_feed_opened": "Зв'язок з тривогою: ця стрічка відкрилась автоматично через небезпеку.",
        "keys_shelter": "Клавіші: 1 моніторинг | 2 укриття | 3 речі | 4 налаштування | A додати укриття | G пошук Google | L вхід | M карта | Q вихід",
        "nearest": "НАЙБЛИЖЧЕ",
        "distance_unknown": "відстань невідома",
        "distance": "Відстань",
        "address": "Адреса",
        "address_not_provided": "адресу не вказано",
        "phone": "телефон",
        "phone_not_provided": "не вказано",
        "open_route_note": "натисни M, щоб відкрити маршрут/пошук у Google Maps",
        "no_shelter_candidates": "Поки немає варіантів укриття.",
        "set_google_hint": "Вкажи GOOGLE_MAPS_API_KEY + USER_LAT + USER_LON, потім натисни G.",
        "add_shelters_hint": "Або додай локальні укриття та станції метро в shelters.json.",
        "press_map_hint": "Натисни M, щоб відкрити пошук Google Maps без API.",
        "last_map_url": "Останнє посилання карти: {url}",
        "settings_header": "Налаштування",
        "supplies_header": "Що взяти з собою",
        "supplies_custom_header": "Налаштувати тривожну сумку",
        "supplies_editor_hint": "Редагуй по одному пункту в рядку: Назва: деталі. Список оновлюється під час вводу.",
        "supplies_empty": "Пунктів тривожної сумки поки немає.",
        "supplies_saved": "Тривожну сумку збережено в {path}.",
        "supplies_save_failed": "Не вдалося зберегти тривожну сумку: {error}",
        "supplies_load_failed": "Не вдалося завантажити власну тривожну сумку: {error}",
        "supplies_reset_done": "Тривожну сумку скинуто до типового списку.",
        "supplies_keys": "Клавіші: 1 моніторинг | 2 укриття | 3 речі | 4 налаштування | A додати укриття | L вхід | M карта | Q вихід",
        "settings_keys": "1 моніторинг | 2 укриття | 3 речі | 4 налаштування | A додати укриття | G оновити | L вхід | M карта | Q вихід",
        "button_cancel": "Скасувати тривогу",
        "button_confirm": "Підтвердити зараз",
        "button_search": "Пошук укриттів",
        "button_auto_shelters": "Авто поруч",
        "button_login": "Вхід Google",
        "button_map": "Відкрити карту",
        "button_language": "Змінити мову",
        "button_add_shelter": "Додати укриття",
        "button_save_supplies": "Зберегти сумку",
        "button_reset_supplies": "Скинути типовий список",
        "button_quit": "Вийти",
        "emergency_contact": "Екстрений контакт",
        "camera": "Камера",
        "live_camera_feed": "Жива камера",
        "camera_online": "ОНЛАЙН",
        "detection_systems": "Системи виявлення",
        "location_status": "Локація",
        "not_set": "не вказано",
        "manual_shelter_header": "Додати укриття",
        "search_query_label": "Пошуковий запит:",
        "shelter_name_label": "Назва укриття:",
        "address_label": "Адреса:",
        "latitude_label": "Широта:",
        "longitude_label": "Довгота:",
        "phone_label": "Телефон:",
        "note_label": "Нотатка:",
        "manual_shelter_hint": "Натисни A після NEW_SHELTER_NAME та адреси або координат.",
        "shelter_add_ready": "A додати укриття з NEW_SHELTER_*",
        "shelter_add_missing": "Вкажи NEW_SHELTER_NAME та адресу або координати перед A.",
        "shelter_added": "Укриття додано: {name}",
        "shelter_add_failed": "Не вдалося додати укриття: {error}",
        "maps_account_hint": "Вхід тримає Google Maps готовими в акаунті браузера для подальшого користування.",
        "demo": "ДЕМО",
        "real": "РЕАЛ",
        "language": "Мова",
        "language_toggled": "Мову змінено на {language}.",
        "google_not_searched": "Google Maps: пошук ще не запускався",
        "google_set_api": "Google Maps: вкажи GOOGLE_MAPS_API_KEY",
        "google_set_api_places": "Google Maps: вкажи GOOGLE_MAPS_API_KEY для пошуку Places",
        "google_waiting_location": "Google Maps: очікується геолокація",
        "google_set_location": "Google Maps: спочатку вкажи USER_LAT та USER_LON",
        "google_searching": "Google Maps: пошук...",
        "google_found": "Google Maps: знайдено {count} варіантів",
        "google_found_shelters": "Google Maps: знайдено {count} варіантів укриття",
        "google_search_running": "Google Maps: пошук уже виконується",
        "google_search_failed": "Помилка пошуку Google Maps: {error}",
        "google_search_fallback": "Google Maps: резервний пошук відкрито в браузері",
        "google_error": "Помилка Google Maps: {message}",
        "auto_location_detecting": "Авто: визначаю геолокацію...",
        "auto_location_found": "Авто: геолокацію визначено.",
        "auto_location_failed": "Авто: не вдалося визначити геолокацію. Вкажи USER_LAT/USER_LON або увімкни служби локації.",
        "auto_shelter_searching": "Авто: шукаю найближчі укриття метро...",
        "auto_shelter_found": "Авто: знайдено {count} найближчих варіантів укриття метро в межах {radius} м.",
        "auto_shelter_no_candidates": "Авто: в межах {radius} м не знайдено укриттів метро.",
        "auto_shelter_failed": "Помилка автопошуку укриттів: {error}",
        "passive_fallback_ready": "Пасивний режим: резервний пошук Google Maps готовий",
        "passive_waiting_location": "Пасивний режим: вкажи USER_LAT та USER_LON для найближчих укриттів",
        "google_shelter_name": "Укриття з Google Maps",
        "google_candidate_note": "Варіант із Google Maps Places",
        "google_candidate_note_desktop": "Знайдено через Google Maps Places API",
        "google_maps_shelter_query": "станція метро укриття",
        "google_maps_near": "поблизу",
        "metro_station_shelter": "Станція метро як укриття",
        "metro_entrance_shelter": "Вхід до метро як укриття",
        "osm_shelter_note": "Знайдено автоматично через OpenStreetMap/Overpass.",
        "google_maps_fallback_name": "Пошук укриттів/метро в Google Maps",
        "google_maps_fallback_note": "Резервний варіант: відкриває пошук укриттів і станцій метро в Google Maps.",
        "google_maps_no_location": "Пошук у Google Maps, USER_LAT/USER_LON не вказано",
        "shelter_file_missing": "Файл укриттів не знайдено: {path}",
        "shelter_file_read_failed": "Не вдалося прочитати файл укриттів {path}: {error}",
        "unnamed_shelter": "Укриття без назви",
        "shelter_map_opened": "Карту укриття відкрито.",
        "open_url": "Відкрий це посилання: {url}",
        "audio_disabled_install": "Аудіо вимкнено: встанови sounddevice через `pip install sounddevice`.",
        "audio_disabled_microphone": "Аудіо вимкнено: не вдалося відкрити мікрофон: {error}",
        "gesture_disabled_install": "Жести вимкнено: встанови mediapipe через `pip install mediapipe`.",
        "gesture_model_missing": "Жести вимкнено: файл моделі не знайдено: {path}",
        "gesture_tasks_failed": "Жести вимкнено: не вдалося створити MediaPipe Tasks HandLandmarker з {path}: {error}",
        "gesture_reinstall_hint": "Спробуй: pip install --upgrade --force-reinstall mediapipe",
        "gestures_disabled": "жести вимкнено",
        "no_hand": "руку не видно",
        "hand_visible": "руку видно",
        "gesture_detected": "Жест: {gesture} {seconds:.1f}с",
        "hand_motion_label": "рух руки {score:.2f}",
        "body_motion_overlay": "рух тіла {direction} {score:.2f} | удар {hit}",
        "body_hit_overlay": "УДАР",
        "hit_yes": "є",
        "hit_no": "немає",
        "direction_unknown": "невідомо",
        "direction_still": "на місці",
        "direction_left": "ліворуч",
        "direction_right": "праворуч",
        "direction_up": "вгору",
        "direction_down": "вниз",
        "disaster_estimate": "Оцінка стихії",
        "safe_area": "немає негайної загрози",
        "disaster_tornado": "Торнадо",
        "disaster_flood": "Повінь",
        "disaster_fire": "Пожежа",
        "hazard_none": "немає",
        "hazard_far": "далеко",
        "hazard_medium": "помірно",
        "hazard_near": "близько",
        "direction_up_left": "вгору ліворуч",
        "direction_up_right": "вгору праворуч",
        "direction_down_left": "вниз ліворуч",
        "direction_down_right": "вниз праворуч",
        "body_direction": "Напрямок",
        "thumbs_up_help_label": "жест великим пальцем вгору",
        "fist_help_label": "жест кулаком",
        "direct_move_help_label": "жест прямого руху",
        "monitoring": "моніторинг",
        "alarm_cancelled": "тривогу скасовано",
        "weapon_detected": "Виявлено зброю: {kind}",
        "knife_detected": "Виявлено ніж",
        "gun_detected": "Виявлено пістолет/стрілецьку зброю",
        "weapon_moving": "Рухома зброя виявлена",
        "object_speed_alert": "Виявлено швидкий рух малого предмета",
        "sharp_impulse_reason": "різкий імпульсний звук: {rms_db:.1f} dBFS, пік {peak:.2f}",
        "sustained_sound_reason": "тривалий гучний високочастотний звук: {rms_db:.1f} dBFS",
        "bright_flash_reason": "різкий яскравий спалах: оцінка {score:.2f}",
        "sudden_motion_reason": "різкий рух: оцінка {score:.2f}",
        "body_direction_reason": "тіло рухається {direction}: оцінка {score:.2f}",
        "body_collision_reason": "виявлено удар/зіткнення тіла {direction}: оцінка {score:.2f}",
        "manual_gesture_reason": "ручний жест допомоги: {gesture}, утримано {seconds:.1f}с",
        "action_cooldown": "Дію пропущено: активна пауза між викликами.",
        "demo_action": "ДЕМО: екстрена дія була б виконана зараз. Номер: {number}. Причина: {reason}",
        "local_action_finished": "Локальну дію завершено з кодом {code}.",
        "twilio_missing": "Реальну дію ввімкнено, але бракує налаштувань Twilio: {missing}",
        "twilio_message": "Автоматичне екстрене сповіщення. Виявлено можливу небезпечну для життя ситуацію. Причина: {reason}. Будь ласка, перевірте та відправте допомогу за потреби.",
        "twilio_sent": "Запит дзвінка Twilio надіслано: HTTP {status}. {body}",
        "twilio_failed": "Не вдалося зробити дзвінок Twilio: {error}",
        "alarm_status": "ТРИВОГА: X скасувати, C подзвонити зараз",
        "desktop_mode_print": "Режим: {mode}",
        "desktop_target_print": "Екстрений номер/контакт: {number}",
        "desktop_keys_print": "Клавіші: Q вихід, X скасувати, C підтвердити, 1 моніторинг, 2 укриття, 3 речі, 4 налаштування, O авто поруч, A додати укриття, G пошук Google, L вхід, M карта, T мова.",
        "desktop_ui_missing": "Desktop UI потребує tkinter і Pillow. Встанови Pillow командою `pip install Pillow`; tkinter входить до стандартного інсталятора Python для Windows.",
        "google_login_required_failed": "Google-вхід обов'язковий, але реєстрацію не завершено.",
        "evidence_saved": "Доказ збережено: {path}",
        "camera_read_failed": "Не вдалося прочитати кадр з камери.",
        "camera_open_failed": "Не вдалося відкрити камеру {index}.",
        "camera_opened_debug": "Камеру відкрито: індекс={index}, isOpened={opened}",
        "window_create_failed": "Не вдалося створити вікно показу: {error}",
        "entering_main_loop": "Вхід у головний цикл і показ вікна",
        "google_account_not_registered": "Google-акаунт: не зареєстровано",
        "google_account_set_client": "Google-акаунт: спочатку вкажи GOOGLE_OAUTH_CLIENT_ID",
        "google_account_callback_failed": "Google-акаунт: не вдалося запустити локальний зворотний виклик: {error}",
        "opening_google_signin": "Відкриваю Google-вхід: {url}",
        "google_login_running": "Google-акаунт: вхід уже виконується",
        "google_account_opened": "Сторінку Google-акаунта відкрито. Для повного OAuth вкажи GOOGLE_OAUTH_CLIENT_ID або GOOGLE_ACCOUNT_EMAIL для локального профілю.",
        "google_profile_saved_env": "Google-акаунт: локальний профіль збережено для {email}",
        "google_account_error": "Google-акаунт: {error}",
        "google_account_timeout": "Google-акаунт: час входу вийшов або його скасовано",
        "google_token_error": "Google-акаунт: помилка токена: {error}",
        "google_profile_error": "Google-акаунт: помилка профілю: {error}",
        "google_profile_incomplete": "Google-акаунт: неповна відповідь профілю Google",
        "google_account_registered": "Google-акаунт: зареєстровано {email}",
        "google_signin_failed_page": "Google-вхід не вдався. Цю вкладку можна закрити.",
        "google_signin_done_page": "Google-вхід завершено. Можна повернутися до StepPrep.",
        "mobile_ready": "Готово",
        "mobile_alarm_active": "ТРИВОГА АКТИВНА",
        "mobile_sos": "SOS / Увімкнути тривогу",
        "mobile_manual_sos": "Ручний мобільний SOS",
        "mobile_dial": "Набрати екстрений контакт",
        "mobile_open_feed": "Відкрити стрічку укриттів",
        "mobile_register_google": "Реєстрація / Google-акаунт",
        "mobile_hooks_note": "Мобільний аналіз аудіо/відео можна підключити після перевірки дозволів Android.",
        "mobile_shelter_feed": "Стрічка укриттів",
        "mobile_search": "Пошук",
        "mobile_map": "Карта",
        "mobile_back": "Назад",
        "mobile_empty_feed": "Поки немає варіантів укриття.\nНатисни Пошук, увімкни Google Maps API або додай укриття/метро в shelters.json.",
        "mobile_open_map": "Відкрити карту",
        "mobile_start_gps": "Увімкнути GPS",
        "mobile_google_oauth": "Відкрити Google OAuth у desktop app",
        "mobile_toggle_language": "Змінити мову",
        "mobile_emergency_contact": "Екстрений контакт: {number}",
        "mobile_location": "Локація: {location}",
        "mobile_maps": "Запит Maps: {query}\nAPI-ключ: {api_key}",
        "mobile_waiting_location": "очікується USER_LAT/USER_LON або GPS",
        "api_configured": "налаштовано",
        "api_not_configured": "не налаштовано",
        "gps_desktop": "GPS доступний в Android-збірці; desktop використовує USER_LAT/USER_LON.",
        "gps_starting": "GPS: запуск...",
        "gps_updated": "GPS: локацію оновлено",
        "mobile_alarm_status": "Тривога: {reason}. Стрічку укриттів відкрито.",
        "not_registered": "не зареєстровано",
        "registered": "зареєстровано",
        "metro_note": "Станції метро також враховуються як варіанти укриття.",
    },
}


class Translator:
    def __init__(self, language: str | None = None) -> None:
        self.language = self.normalize(language or os.getenv("APP_LANG") or os.getenv("RESCUE_LANG") or "uk")

    @staticmethod
    def normalize(language: str) -> str:
        language = (language or "uk").lower().strip()
        if language.startswith("en"):
            return "en"
        if language.startswith("uk") or language.startswith("ua"):
            return "uk"
        return "uk"

    def set_language(self, language: str) -> None:
        self.language = self.normalize(language)

    def toggle(self) -> str:
        self.language = "en" if self.language == "uk" else "uk"
        return self.language

    def language_name(self) -> str:
        return self.t("lang_name")

    def t(self, key: str, **kwargs: Any) -> str:
        value = TRANSLATIONS.get(self.language, TRANSLATIONS["uk"]).get(key)
        if value is None:
            value = TRANSLATIONS["en"].get(key, key)
        if kwargs:
            try:
                return value.format(**kwargs)
            except (KeyError, ValueError):
                return value
        return value


def get_translator(language: str | None = None) -> Translator:
    return Translator(language)
